apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tdemo-gateway-cert
  namespace: default
spec:
  dnsNames:
  - tdemo.h2o.kubecorn.com
  secretName: tapfynesycom
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
